# Generated by Django 5.2.6 on 2025-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("fullname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=16)),
                ("confirmpassword", models.CharField(max_length=16)),
            ],
        ),
    ]
