# Generated by Django 5.2.6 on 2025-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="studentcourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=30)),
                ("course_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("hours_spent", models.IntegerField(default=0)),
                ("completion_percentage", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
