# Generated by Django 5.2.6 on 2025-09-28 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_studentcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
